# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  build-with-docker:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${CIRCLE_PROJECT_REPONAME}"
          tag: "${CIRCLE_BUILD_NUM}"